import type { Deal, Category } from './schema';

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: 'Electronics', slug: 'electronics', icon: 'smartphone', order: 1 },
  { id: 2, name: 'Fashion', slug: 'fashion', icon: 'shirt', order: 2 },
  { id: 3, name: 'Food & Dining', slug: 'food', icon: 'utensils', order: 3 },
  { id: 4, name: 'Home & Kitchen', slug: 'home', icon: 'home', order: 4 },
  { id: 5, name: 'Beauty & Care', slug: 'beauty', icon: 'sparkles', order: 5 },
  { id: 6, name: 'Travel & Flights', slug: 'travel', icon: 'plane', order: 6 },
  { id: 7, name: 'Daily Essentials', slug: 'essentials', icon: 'shopping-bag', order: 7 },
];

export const MOCK_DEALS: Deal[] = [
  {
    id: 101,
    title: 'Apple AirPods Pro (2nd Gen) with MagSafe USB-C Case — ANC & Spatial Audio',
    description: 'Lowest price ever on Amazon! Features Apple H2 headphone chip, up to 2x more Active Noise Cancellation, personalized Spatial Audio, and up to 30 hours of total listening time.',
    originalPrice: 24900,
    dealPrice: 18999,
    discountPct: 24,
    affiliateUrl: 'https://amazon.in/dp/B0CHX3TW6H?tag=autoclaimer-21',
    sourceUrl: 'https://amazon.in/dp/B0CHX3TW6H',
    imageUrl: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&auto=format&fit=crop&q=80',
    platform: 'Amazon',
    categoryId: 1,
    isActive: true,
    isExpired: false,
    isFeatured: true,
    source: 'manual',
    sourceMsgId: 'tg_101',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  },
  {
    id: 102,
    title: 'Sony WH-1000XM5 Wireless Industry Leading Noise Cancelling Headphones',
    description: 'Ultra premium noise cancellation with 8 microphones, Auto NC Optimizer, crystal clear hands-free calling, and 30-hour battery life with quick charging.',
    originalPrice: 34990,
    dealPrice: 26990,
    discountPct: 23,
    affiliateUrl: 'https://amazon.in/dp/B09XS7JWHH?tag=autoclaimer-21',
    sourceUrl: 'https://amazon.in/dp/B09XS7JWHH',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    platform: 'Amazon',
    categoryId: 1,
    isActive: true,
    isExpired: false,
    isFeatured: true,
    source: 'manual',
    sourceMsgId: 'tg_102',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  },
  {
    id: 103,
    title: 'Levi’s Men 511 Slim Fit Mid-Rise Jeans — Deep Dark Indigo',
    description: 'Crazy loot discount on official Levi’s store via Flipkart! Premium stretch denim fabric with classic 5-pocket styling. Limited sizes available.',
    originalPrice: 3999,
    dealPrice: 1199,
    discountPct: 70,
    affiliateUrl: 'https://flipkart.com/levis-jeans/p/itm123?affid=autoclaimer',
    sourceUrl: 'https://flipkart.com/levis-jeans/p/itm123',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-780932375a4a?w=600&auto=format&fit=crop&q=80',
    platform: 'Flipkart',
    categoryId: 2,
    isActive: true,
    isExpired: false,
    isFeatured: true,
    source: 'manual',
    sourceMsgId: 'tg_103',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  },
  {
    id: 104,
    title: 'Samsung 108 cm (43 inches) Crystal iSmart 4K Ultra HD Smart LED TV',
    description: 'Crazy price drop on Samsung Crystal 4K! Includes PurColor, Crystal Processor 4K, Smart Hub, and 20W sound output with Q-Symphony.',
    originalPrice: 52900,
    dealPrice: 28990,
    discountPct: 45,
    affiliateUrl: 'https://amazon.in/dp/B0C1H2345?tag=autoclaimer-21',
    sourceUrl: 'https://amazon.in/dp/B0C1H2345',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&auto=format&fit=crop&q=80',
    platform: 'Amazon',
    categoryId: 1,
    isActive: true,
    isExpired: false,
    isFeatured: false,
    source: 'telegram',
    sourceMsgId: 'tg_104',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  },
  {
    id: 105,
    title: 'Puma Men Running Shoes — Lightweight & Breathable Mesh',
    description: 'Flat 65% OFF on Puma genuine running shoes on Myntra! Cushioned EVA midsole, durable rubber outsole, and ultra-stylish look.',
    originalPrice: 4499,
    dealPrice: 1574,
    discountPct: 65,
    affiliateUrl: 'https://myntra.com/shoes/puma/1234?tag=autoclaimer',
    sourceUrl: 'https://myntra.com/shoes/puma/1234',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    platform: 'Myntra',
    categoryId: 2,
    isActive: true,
    isExpired: false,
    isFeatured: true,
    source: 'manual',
    sourceMsgId: 'tg_105',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  },
  {
    id: 106,
    title: 'Swiggy Gourmet Feast Coupon — Flat ₹175 OFF on ₹499+ Orders',
    description: 'Applicable on select top-rated restaurants across Bangalore, Mumbai, Delhi, and Hyderabad. Use code FEAST175 at checkout during dinner time.',
    originalPrice: 499,
    dealPrice: 324,
    discountPct: 35,
    affiliateUrl: 'https://swiggy.com/offers',
    sourceUrl: 'https://swiggy.com/offers',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
    platform: 'Swiggy',
    categoryId: 3,
    isActive: true,
    isExpired: false,
    isFeatured: false,
    source: 'telegram',
    sourceMsgId: 'tg_106',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  },
  {
    id: 107,
    title: 'Philips Air Fryer HD9252/90 with Rapid Air Technology (4.1 Liter)',
    description: 'Fry, bake, grill, roast and reheat with up to 90% less fat! Touch screen with 7 presets, keep warm function, and dishwasher-safe parts.',
    originalPrice: 11995,
    dealPrice: 6999,
    discountPct: 42,
    affiliateUrl: 'https://amazon.in/dp/B0987654?tag=autoclaimer-21',
    sourceUrl: 'https://amazon.in/dp/B0987654',
    imageUrl: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
    platform: 'Amazon',
    categoryId: 4,
    isActive: true,
    isExpired: false,
    isFeatured: false,
    source: 'manual',
    sourceMsgId: 'tg_107',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  },
  {
    id: 108,
    title: 'Maybelline New York Fit Me Matte + Poreless Liquid Foundation (30ml)',
    description: 'Bestselling foundation at 50% discount! Lightweight, natural matte finish that blurs pores and controls shine up to 16 hours.',
    originalPrice: 649,
    dealPrice: 324,
    discountPct: 50,
    affiliateUrl: 'https://nykaa.com/maybelline-fit-me?tag=autoclaimer',
    sourceUrl: 'https://nykaa.com/maybelline-fit-me',
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&auto=format&fit=crop&q=80',
    platform: 'Nykaa',
    categoryId: 5,
    isActive: true,
    isExpired: false,
    isFeatured: false,
    source: 'telegram',
    sourceMsgId: 'tg_108',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  },
  {
    id: 109,
    title: 'MakeMyTrip Domestic Flight Coupon — Instant ₹1,500 OFF on IndiGo & Air India',
    description: 'Book any roundtrip domestic flight booking worth ₹7,500 or more using code FLYAUTO on MakeMyTrip app or website. Valid till midnight!',
    originalPrice: 7500,
    dealPrice: 6000,
    discountPct: 20,
    affiliateUrl: 'https://makemytrip.com/flights',
    sourceUrl: 'https://makemytrip.com/flights',
    imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600&auto=format&fit=crop&q=80',
    platform: 'MakeMyTrip',
    categoryId: 6,
    isActive: true,
    isExpired: false,
    isFeatured: true,
    source: 'manual',
    sourceMsgId: 'tg_109',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  },
  {
    id: 110,
    title: 'Surf Excel Matic Liquid Detergent Front Load (2 Liter Mega Pack)',
    description: 'Super saver deal on Amazon grocery! Tough stain removal right in the machine with superior fragrance and zero detergent residue.',
    originalPrice: 470,
    dealPrice: 329,
    discountPct: 30,
    affiliateUrl: 'https://amazon.in/dp/B07987?tag=autoclaimer-21',
    sourceUrl: 'https://amazon.in/dp/B07987',
    imageUrl: 'https://images.unsplash.com/photo-1585816019856-5b5120a109a4?w=600&auto=format&fit=crop&q=80',
    platform: 'Amazon',
    categoryId: 7,
    isActive: true,
    isExpired: false,
    isFeatured: false,
    source: 'telegram',
    sourceMsgId: 'tg_110',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  },
  {
    id: 111,
    title: 'OnePlus Nord Buds 2r True Wireless in Ear Earbuds with 12.4mm Drivers',
    description: 'Deep punchy bass, dual mic AI clear call noise cancellation, up to 38 hours of playtime, and IP55 water & sweat resistance.',
    originalPrice: 2299,
    dealPrice: 1699,
    discountPct: 26,
    affiliateUrl: 'https://amazon.in/dp/B0C8V8?tag=autoclaimer-21',
    sourceUrl: 'https://amazon.in/dp/B0C8V8',
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
    platform: 'Amazon',
    categoryId: 1,
    isActive: true,
    isExpired: false,
    isFeatured: false,
    source: 'manual',
    sourceMsgId: 'tg_111',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  },
  {
    id: 112,
    title: 'Allen Solly Men Classic Regular Fit Pure Cotton Polo T-Shirt',
    description: 'Multiple color options available! Soft breathable cotton pique fabric with ribbed collar and cuffs. Perfect everyday casual wear.',
    originalPrice: 1099,
    dealPrice: 449,
    discountPct: 59,
    affiliateUrl: 'https://amazon.in/dp/B08765?tag=autoclaimer-21',
    sourceUrl: 'https://amazon.in/dp/B08765',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
    platform: 'Amazon',
    categoryId: 2,
    isActive: true,
    isExpired: false,
    isFeatured: false,
    source: 'telegram',
    sourceMsgId: 'tg_112',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  },
  {
    id: 113,
    title: 'Zomato Gold 3-Month Membership — Unlimited Free Delivery & Dining Offers',
    description: 'Get 3 months of Zomato Gold at a fraction of the regular cost. Enjoy zero delivery fee on all orders above ₹199 and VIP dining discounts.',
    originalPrice: 999,
    dealPrice: 99,
    discountPct: 90,
    affiliateUrl: 'https://zomato.com/gold',
    sourceUrl: 'https://zomato.com/gold',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop&q=80',
    platform: 'Zomato',
    categoryId: 3,
    isActive: true,
    isExpired: false,
    isFeatured: true,
    source: 'telegram',
    sourceMsgId: 'tg_113',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  },
  {
    id: 114,
    title: 'Prestige IRIS Plus 750 Watt Mixer Grinder with 3 Stainless Steel Jars + Juicer',
    description: 'Heavy duty 750W motor, ergonomic handles, overload protection switch, and multipurpose jars for effortless Indian cooking.',
    originalPrice: 6195,
    dealPrice: 2899,
    discountPct: 53,
    affiliateUrl: 'https://flipkart.com/prestige-mixer/p/itm456?affid=autoclaimer',
    sourceUrl: 'https://flipkart.com/prestige-mixer/p/itm456',
    imageUrl: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=600&auto=format&fit=crop&q=80',
    platform: 'Flipkart',
    categoryId: 4,
    isActive: true,
    isExpired: false,
    isFeatured: false,
    source: 'manual',
    sourceMsgId: 'tg_114',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  },
  {
    id: 115,
    title: 'Minimalist 10% Niacinamide Face Serum for Acne Marks & Oil Control (30ml)',
    description: 'Dermatologist tested formula with pure zinc and hyaluronic acid. Reduces blemishes, evens out skin tone, and strengthens skin barrier.',
    originalPrice: 599,
    dealPrice: 479,
    discountPct: 20,
    affiliateUrl: 'https://amazon.in/dp/B08C98?tag=autoclaimer-21',
    sourceUrl: 'https://amazon.in/dp/B08C98',
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80',
    platform: 'Amazon',
    categoryId: 5,
    isActive: true,
    isExpired: false,
    isFeatured: false,
    source: 'manual',
    sourceMsgId: 'tg_115',
    createdAt: new Date().toISOString(),
    expiresAt: null,
  }
];
